project:
  type: website
  output-dir: docs
  resources: 
  - "files/*"
  - "files/images/*"
  - "art22/*"
  - "art22/images/*"

execute:
  cache: true

website:
  title: "Justin Liu"
  favicon: files/icon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
  search: false
  google-analytics: "G-ZN184D6GCQ"

format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true
    embed-resources: true

editor: visual
