project:
  type: website
  output-dir: docs

website:
  title: "Justin Liu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - courses.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true

editor: visual

