project:
  type: website
  output-dir: docs

website:
  title: "Justin Liu"
  favicon: files/icon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    embed-resources: true

editor: visual

