---
title: "Coursework"
---

```{r, include=FALSE}
library(kableExtra)

python_text <- function() text_spec("Python", color = "green")
r_text <- function() text_spec("R", color = "#ff9600")
sql_text <- function() text_spec("SQL", color = "#5bb0ff")
max_text <- function() text_spec("Max", color = "#F6BE00")
java_text <- function() text_spec("Java", color = "red")
godot_text <- function() text_spec("Godot", color = "purple")
html_css_text <- function() text_spec("HTML/CSS", color = "#f266ff")
arcgis_text <- function() text_spec("ArcGIS StoryMaps", color = "#1cc7ba")
```

## Computer Science

-   **CMPSC 8:** Introduction to Computer Science (`r python_text()`)
-   **CMPSC 9:** Intermediate Python (`r python_text()`)

## Statistics and Data Science

-   **CMPSC 5A-B:** Introduction to Data Science (`r python_text()`)
-   **EEMB 146:** Biostatistics (`r r_text()`)
-   **PSTAT 10:** Data Science Principles (`r r_text()` & `r sql_text()`)
-   **PSTAT 100:** Data Science Concepts and Analysis (`r python_text()`)
-   **PSTAT 120A-B:** Probability and Statistics
-   **PSTAT 122:** Design and Analysis of Experiments
-   **PSTAT 126:** Regression Analysis (`r r_text()`)
-   **PSTAT 127:** Advanced Statistical Models (`r r_text()`)
-   **PSTAT 131:** Statistical Machine Learning (`r r_text()`)
-   **PSTAT 134:** Statistical Data Science (`r r_text()`)
-   **PSTAT 135:** Big Data Analytics (`r python_text()` & `r sql_text()`)
-   **PSTAT 160A:** Stochastic Processes (`r python_text()`)
-   **PSTAT 174:** Time Series (`r r_text()`)
-   **PSTAT 190:** Teaching and Mentoring Statistics and Data Science
-   **PSTAT 194CS:** Computational Statistics (`r r_text()`)
-   **PSTAT 197A-B-C:** Data Science Capstone (`r r_text()` & `r python_text()`)

## Math

-   **MATH 4A:** Linear Algebra
-   **MATH 4B:** Differential Equations
-   **MATH 6A:** Vector Calculus
-   **MATH 8:** Transition to Higher Mathematics
-   **MATH 117:** Methods of Analysis

## Creative Coding

-   **ART 22:** Computer Programming for the Arts (`r java_text()` & `r html_css_text()`)
-   **LING 194:** Beyond Duolingo: Digital Games for Language Learning (`r godot_text()`)
-   **MUS 109CA:** Introduction to Interactive Audio (`r max_text()`)
-   **RG ST 190DM:** Transnational Buddhism through Digital Mapping (`r arcgis_text()`)

## Linguistics

-   **LING 20:** Language and Linguistics
-   **LING 102:** Programming for Linguists (`r python_text()`)
-   **LING 104:** Statistical Methods in Linguistics (`r r_text()`)
-   **LING 105:** Predictive Modeling in Linguistics (`r r_text()`)
-   **LING 106:** Introduction to Phonology
-   **LING 110:** Foundations of Computational Linguistics (`r python_text()`)
-   **LING 111:** Advanced Computational Linguistics: Text Processing (`r python_text()`)

## Other Classes I Enjoyed

-   **C LIT 152:** Digital Humanities Practice (`r python_text()`)
-   **JAPAN 63:** Sociology of Japan
-   **JAPAN 165:** Popular Culture in Japan
-   **MUS 11:** Fundamentals of Music
