---
title: "Projects"
---

```{r, include=FALSE}
library(kableExtra)

python_text <- function() text_spec("Python", color = "green")

r_text <- function() text_spec("R", color = "#ff9600")
```

## R

-   **Predicting Anime Scores** \| `r r_text()` \| [code](https://github.com/hillfields/predicting-anime-scores)
    -   Built a Shiny app to predict MyAnimeList scores with tidymodels
-   **Clustering Analysis on Country Data** \| `r r_text()` \| [code](https://github.com/pstat197/vignette-clustering-methods), [vignette](files/clustering-vignette.html)
    -   Implemented unsupervised clustering methods to group countries based on socioeconomic and health conditions
-   **Modeling Japan's Activity Rates in the 21st Century** \| `r r_text()` \| [code](https://github.com/hillfields/modeling-activity-rates), [report](files/modeling-activity-rates.pdf)
    -   Modeled and forecasted monthly activity rates in Japan for the years 2000-2021 using a SARIMA model
-   **Analyzing the 2020 Presidential Election** \| `r r_text()` \| [report](files/election-analysis.html)
    -   Experimented with several classification models to predict the winning candidate for each county, achieving a test classification accuracy of 93.5%
-   **Predicting Data Science and STEM Salaries with Permutation Tests and Bootstrapping** \| `r r_text()` \| [report](files/mc-simulation-salaries.pdf)
    -   Used Monte Carlo methods to predict data science and STEM salaries

## Python

-   **Analyzing Voter Turnout in Alaska for the 2016 General Election** \| `r python_text()` \| [report](files/voter-turnout.html)
    -   Looked into how demographic factors played a role in whether Alaskan citizens voted in the 2016 general election
-   **Analyzing UCSB Grades During Remote Instruction** \| `r python_text()` \| [report](files/ucsb-pandemic-grades.html)
    -   Investigated the impact of online learning on UCSB students' grades during the COVID-19 pandemic
-   **Lyrics Frequency Visualizer** \| `r python_text()` \| [code](https://github.com/hillfields/lyrics-frequency-visualizer)
    -   Made a simple app to access the Spotify API, scrape Japanese song lyrics, and visualize their word frequencies

## Creative Coding

-   **Art Portfolio** \| `r text_spec("Processing / Java", color = "red")` \| [code](https://github.com/hillfields/creative-coding-processing), [site](https://class.arts.ucsb.edu/art22/Sites/s_22/LiuJustin/)
    -   Created interactive art pieces using the Processing graphics library in Java
    -   Designed the website to host the projects from scratch using HTML/CSS
-   **Language Learning Game** \| `r text_spec("Godot", color = "purple")` \| [code](https://github.com/aventayolboada/LING194_Class_project_M21)
    -   Worked with other students to build a game for learning Mixtec
-   **Interactive Audio Projects** \| `r text_spec("Max", color = "#f1c232")` \| [site](mus-109ca.html)
    -   Utilized the visual programming language Max for several creative music projects
-   **American Buddhist Meditation Temple StoryMap** \| `r text_spec("ArcGIS StoryMaps", color = "#82bef7")` \| [site](https://storymaps.arcgis.com/stories/48e3c1a6290e4bb1a3fadd5bc979e7f9)
    -   Collaborated with other students to map the history of the American Buddhist Meditation Temple in Santa Barbara, CA

## Linguistics

-   **Phonetic Description of Japanese** \| [report](files/japanese-phonology.pdf)
    -   Researched the basic phonology of Japanese, including its pitch accent patterns
